In [4]:
import pandas as pd
import re

# Fungsi pembersihan teks
def clean_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#\w+", "", text)
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [5]:
# Load dataset
df = pd.read_csv("../data/raw/yt_6500.csv")

# Tampilkan 20 data pertama
df.head(20)

                                                 text  label
0          CANTIKA ABIGAIL TAU MEDAN MAGNET PASUKAN 😂      0
1                                Tau curi umur juga 😆      0
2                                         Hahhahaahaa      0
3   ibunya cantika dulu artis penyanyi...lagunya h...      0
4                             Ini sih gilaaa yaaa😂😂😂😂      0
5             KELUARKAN EPISODE KETUA NAGA HITAM KAMI      0
6                     Sesepu joglonya @dustin tiffani      0
7   Dia ketawa aja merdu, pake nada pula 😅 Minder ...      0
8   Gue denger2in jegel ni kalo mau nanya kebanyak...      0
9   wak.. mak ber,&harahap lucu juga kali kalau di...      0
10                                                 🤣😂      0
11            bang boris cocok sama cantika, HAHAHAHA      0
12                            Keladi dikukus enak bgt      0
13  6:45 7:16 Obt KB yg mhalpun tdk mnjamin ya sma...      0
14  UPH MUSIK jga, apa yang dijelaskan beneran wkwkwk      0
15                       26:28 "dari klaten" WKWKWKWK      0
16  Kalo opa nya crish patikkawa, oma nya rina Has...      0
17  Wajar kalo popularitas ⭐ A L E X I S 1 7 ⭐ mel...      1
18  Cara daftar ⭐ A L E X I S 1 7 ⭐ juga simpel, c...      1
19  Nggak perlu nunggu lama, ⭐ A L E X I S 1 7 ⭐ l...      1

In [6]:
# Bersihkan teks
df["text"] = df["text"].apply(clean_text)

# Cek hasil
df.head(20)

                                                 text  label
0            cantika abigail tau medan magnet pasukan      0
1                                  tau curi umur juga      0
2                                         hahhahaahaa      0
3   ibunya cantika dulu artis penyanyi lagunya hit...      0
4                                 ini sih gilaaa yaaa      0
5             keluarkan episode ketua naga hitam kami      0
6                             sesepu joglonya tiffani      0
7   dia ketawa aja merdu pake nada pula minder bgt...      0
8   gue denger2in jegel ni kalo mau nanya kebanyak...      0
9   wak mak ber harahap lucu juga kali kalau di un...      0
10                                                         0
11             bang boris cocok sama cantika hahahaha      0
12                            keladi dikukus enak bgt      0
13  6 45 7 16 obt kb yg mhalpun tdk mnjamin ya sma...      0
14   uph musik jga apa yang dijelaskan beneran wkwkwk      0
15                         26 28 dari klaten wkwkwkwk      0
16  kalo opa nya crish patikkawa oma nya rina hasy...      0
17  wajar kalo popularitas a l e x i s 1 7 meledak...      1
18  cara daftar a l e x i s 1 7 juga simpel cocok ...      1
19  nggak perlu nunggu lama a l e x i s 1 7 langsu...      1

In [7]:
# Simpan hasil preprocess
df.to_csv("../data/processed/yt_clean.csv", index=False)